import Foundation

extension VehicleProfileTemplate {
    static let templates: [VehicleProfileTemplate] = [
        VehicleProfileTemplate(id: "mini_aceman_e", brand: "MINI", modelName: "Aceman E", displayName: "MINI Aceman E", usableBatteryKWh: 38.5, wltpRangeKm: 309, peakDCChargingKW: 75),
        VehicleProfileTemplate(id: "mini_aceman_se", brand: "MINI", modelName: "Aceman SE", displayName: "MINI Aceman SE", usableBatteryKWh: 49.2, wltpRangeKm: 405, peakDCChargingKW: 95),
        VehicleProfileTemplate(id: "mini_j01_cooper_e", brand: "MINI", modelName: "Cooper E (J01)", displayName: "MINI Cooper E (J01)", usableBatteryKWh: 36.6, wltpRangeKm: 305, peakDCChargingKW: 75),
        VehicleProfileTemplate(id: "mini_f56_cooper_se_2019_2023", brand: "MINI", modelName: "Cooper SE (F56, 2019–2023)", displayName: "MINI Cooper SE (F56, 2019–2023)", usableBatteryKWh: 28.9, wltpRangeKm: 234, peakDCChargingKW: 50),
        VehicleProfileTemplate(id: "mini_j01_cooper_se", brand: "MINI", modelName: "Cooper SE (J01)", displayName: "MINI Cooper SE (J01)", usableBatteryKWh: 49.2, wltpRangeKm: 402, peakDCChargingKW: 95),
        VehicleProfileTemplate(id: "mini_countryman_e", brand: "MINI", modelName: "Countryman E", displayName: "MINI Countryman E", usableBatteryKWh: 64.7, wltpRangeKm: 462, peakDCChargingKW: 130),
        VehicleProfileTemplate(id: "mini_countryman_se_all4", brand: "MINI", modelName: "Countryman SE ALL4", displayName: "MINI Countryman SE ALL4", usableBatteryKWh: 64.7, wltpRangeKm: 433, peakDCChargingKW: 130),
        VehicleProfileTemplate(id: "audi_a6_etron", brand: "Audi", modelName: "A6 e-tron", displayName: "Audi A6 e-tron", usableBatteryKWh: 94.9, wltpRangeKm: 700, peakDCChargingKW: 270),
        VehicleProfileTemplate(id: "audi_q4_45", brand: "Audi", modelName: "Q4 e-tron 45", displayName: "Audi Q4 e-tron 45", usableBatteryKWh: 77, wltpRangeKm: 550, peakDCChargingKW: 175),
        VehicleProfileTemplate(id: "audi_q4_55", brand: "Audi", modelName: "Q4 e-tron 55", displayName: "Audi Q4 e-tron 55", usableBatteryKWh: 77, wltpRangeKm: 563, peakDCChargingKW: 185),
        VehicleProfileTemplate(id: "audi_q6", brand: "Audi", modelName: "Q6 e-tron", displayName: "Audi Q6 e-tron", usableBatteryKWh: 94.9, wltpRangeKm: 625, peakDCChargingKW: 270),
        VehicleProfileTemplate(id: "audi_sq6", brand: "Audi", modelName: "SQ6 e-tron", displayName: "Audi SQ6 e-tron", usableBatteryKWh: 94.9, wltpRangeKm: 598, peakDCChargingKW: 270),
        VehicleProfileTemplate(id: "bmw_i4_edrive35", brand: "BMW", modelName: "i4 eDrive35", displayName: "BMW i4 eDrive35", usableBatteryKWh: 67.1, wltpRangeKm: 500, peakDCChargingKW: 180),
        VehicleProfileTemplate(id: "bmw_i4_edrive40", brand: "BMW", modelName: "i4 eDrive40", displayName: "BMW i4 eDrive40", usableBatteryKWh: 81.3, wltpRangeKm: 600, peakDCChargingKW: 205),
        VehicleProfileTemplate(id: "bmw_i4_m50", brand: "BMW", modelName: "i4 M50", displayName: "BMW i4 M50", usableBatteryKWh: 81.3, wltpRangeKm: 520, peakDCChargingKW: 205),
        VehicleProfileTemplate(id: "bmw_ix1_edrive20", brand: "BMW", modelName: "iX1 eDrive20", displayName: "BMW iX1 eDrive20", usableBatteryKWh: 64.7, wltpRangeKm: 474, peakDCChargingKW: 130),
        VehicleProfileTemplate(id: "bmw_ix1_xdrive30", brand: "BMW", modelName: "iX1 xDrive30", displayName: "BMW iX1 xDrive30", usableBatteryKWh: 64.7, wltpRangeKm: 439, peakDCChargingKW: 130),
        VehicleProfileTemplate(id: "bmw_ix2_edrive20", brand: "BMW", modelName: "iX2 eDrive20", displayName: "BMW iX2 eDrive20", usableBatteryKWh: 64.7, wltpRangeKm: 478, peakDCChargingKW: 130),
        VehicleProfileTemplate(id: "cupra_born_59_eboost", brand: "Cupra", modelName: "Born 59 kWh e-Boost", displayName: "Cupra Born 59 kWh e-Boost", usableBatteryKWh: 59, wltpRangeKm: 427, peakDCChargingKW: 165),
        VehicleProfileTemplate(id: "cupra_born_79_eboost", brand: "Cupra", modelName: "Born 79 kWh e-Boost", displayName: "Cupra Born 79 kWh e-Boost", usableBatteryKWh: 79, wltpRangeKm: 570, peakDCChargingKW: 175),
        VehicleProfileTemplate(id: "cupra_tavascan_endurance", brand: "Cupra", modelName: "Tavascan Endurance", displayName: "Cupra Tavascan Endurance", usableBatteryKWh: 77, wltpRangeKm: 568, peakDCChargingKW: 135),
        VehicleProfileTemplate(id: "cupra_tavascan_vz", brand: "Cupra", modelName: "Tavascan VZ", displayName: "Cupra Tavascan VZ", usableBatteryKWh: 77, wltpRangeKm: 522, peakDCChargingKW: 135),
        VehicleProfileTemplate(id: "ford_capri_er", brand: "Ford", modelName: "Capri Extended Range", displayName: "Ford Capri Extended Range", usableBatteryKWh: 77, wltpRangeKm: 620, peakDCChargingKW: 185),
        VehicleProfileTemplate(id: "ford_capri_extended_range_rwd", brand: "Ford", modelName: "Capri Extended Range RWD", displayName: "Ford Capri Extended Range RWD", usableBatteryKWh: 77, wltpRangeKm: 627, peakDCChargingKW: 185),
        VehicleProfileTemplate(id: "ford_explorer_er", brand: "Ford", modelName: "Explorer Extended Range", displayName: "Ford Explorer Extended Range", usableBatteryKWh: 77, wltpRangeKm: 600, peakDCChargingKW: 185),
        VehicleProfileTemplate(id: "ford_explorer_extended_range_awd", brand: "Ford", modelName: "Explorer Extended Range AWD", displayName: "Ford Explorer Extended Range AWD", usableBatteryKWh: 77, wltpRangeKm: 566, peakDCChargingKW: 185),
        VehicleProfileTemplate(id: "ford_explorer_extended_range_rwd", brand: "Ford", modelName: "Explorer Extended Range RWD", displayName: "Ford Explorer Extended Range RWD", usableBatteryKWh: 77, wltpRangeKm: 602, peakDCChargingKW: 185),
        VehicleProfileTemplate(id: "ford_explorer_standard_range_rwd", brand: "Ford", modelName: "Explorer Standard Range RWD", displayName: "Ford Explorer Standard Range RWD", usableBatteryKWh: 52, wltpRangeKm: 384, peakDCChargingKW: 145),
        VehicleProfileTemplate(id: "ford_mache_er", brand: "Ford", modelName: "Mustang Mach-E Extended Range", displayName: "Ford Mustang Mach-E Extended Range", usableBatteryKWh: 91, wltpRangeKm: 600, peakDCChargingKW: 150),
        VehicleProfileTemplate(id: "ford_mustang_mach_e_premium_rwd", brand: "Ford", modelName: "Mustang Mach-E Premium RWD", displayName: "Ford Mustang Mach-E Premium RWD", usableBatteryKWh: 88, wltpRangeKm: 600, peakDCChargingKW: 150),
        VehicleProfileTemplate(id: "hyundai_ioniq5_lr_awd", brand: "Hyundai", modelName: "Ioniq 5 Long Range AWD", displayName: "Hyundai Ioniq 5 Long Range AWD", usableBatteryKWh: 77.4, wltpRangeKm: 515, peakDCChargingKW: 233),
        VehicleProfileTemplate(id: "hyundai_ioniq5_lr", brand: "Hyundai", modelName: "Ioniq 5 Long Range RWD", displayName: "Hyundai Ioniq 5 Long Range RWD", usableBatteryKWh: 77.4, wltpRangeKm: 570, peakDCChargingKW: 233),
        VehicleProfileTemplate(id: "hyundai_ioniq5_sr", brand: "Hyundai", modelName: "Ioniq 5 Standard Range", displayName: "Hyundai Ioniq 5 Standard Range", usableBatteryKWh: 60, wltpRangeKm: 440, peakDCChargingKW: 220),
        VehicleProfileTemplate(id: "hyundai_ioniq6_lr_awd", brand: "Hyundai", modelName: "Ioniq 6 Long Range AWD", displayName: "Hyundai Ioniq 6 Long Range AWD", usableBatteryKWh: 77.4, wltpRangeKm: 583, peakDCChargingKW: 233),
        VehicleProfileTemplate(id: "hyundai_ioniq6_lr", brand: "Hyundai", modelName: "Ioniq 6 Long Range RWD", displayName: "Hyundai Ioniq 6 Long Range RWD", usableBatteryKWh: 77.4, wltpRangeKm: 614, peakDCChargingKW: 233),
        VehicleProfileTemplate(id: "hyundai_kona_48", brand: "Hyundai", modelName: "Kona Electric 48 kWh", displayName: "Hyundai Kona Electric 48 kWh", usableBatteryKWh: 46, wltpRangeKm: 377, peakDCChargingKW: 100),
        VehicleProfileTemplate(id: "hyundai_kona_65", brand: "Hyundai", modelName: "Kona Electric 65 kWh", displayName: "Hyundai Kona Electric 65 kWh", usableBatteryKWh: 64.8, wltpRangeKm: 514, peakDCChargingKW: 102),
        VehicleProfileTemplate(id: "kia_ev3_long_range", brand: "Kia", modelName: "EV3 Long Range", displayName: "Kia EV3 Long Range", usableBatteryKWh: 78, wltpRangeKm: 605, peakDCChargingKW: 128),
        VehicleProfileTemplate(id: "kia_ev3_standard_range", brand: "Kia", modelName: "EV3 Standard Range", displayName: "Kia EV3 Standard Range", usableBatteryKWh: 55, wltpRangeKm: 436, peakDCChargingKW: 102),
        VehicleProfileTemplate(id: "kia_ev6_long_range_awd", brand: "Kia", modelName: "EV6 Long Range AWD", displayName: "Kia EV6 Long Range AWD", usableBatteryKWh: 74, wltpRangeKm: 506, peakDCChargingKW: 240),
        VehicleProfileTemplate(id: "kia_ev6_long_range_rwd", brand: "Kia", modelName: "EV6 Long Range RWD", displayName: "Kia EV6 Long Range RWD", usableBatteryKWh: 74, wltpRangeKm: 528, peakDCChargingKW: 240),
        VehicleProfileTemplate(id: "kia_ev6_lr", brand: "Kia", modelName: "EV6 Long Range RWD", displayName: "Kia EV6 Long Range RWD", usableBatteryKWh: 77.4, wltpRangeKm: 580, peakDCChargingKW: 233),
        VehicleProfileTemplate(id: "kia_ev9_awd", brand: "Kia", modelName: "EV9 99.8 kWh AWD", displayName: "Kia EV9 99.8 kWh AWD", usableBatteryKWh: 96, wltpRangeKm: 505, peakDCChargingKW: 210),
        VehicleProfileTemplate(id: "kia_ev9_rwd", brand: "Kia", modelName: "EV9 99.8 kWh RWD", displayName: "Kia EV9 99.8 kWh RWD", usableBatteryKWh: 96, wltpRangeKm: 563, peakDCChargingKW: 210),
        VehicleProfileTemplate(id: "polestar_2_long_range_dual_motor_my26", brand: "Polestar", modelName: "2 Long Range Dual Motor", displayName: "Polestar 2 Long Range Dual Motor", usableBatteryKWh: 79, wltpRangeKm: 596, peakDCChargingKW: 205),
        VehicleProfileTemplate(id: "polestar_2_long_range_single_motor_my26", brand: "Polestar", modelName: "2 Long Range Single Motor", displayName: "Polestar 2 Long Range Single Motor", usableBatteryKWh: 79, wltpRangeKm: 659, peakDCChargingKW: 205),
        VehicleProfileTemplate(id: "polestar_2_lrsm", brand: "Polestar", modelName: "2 Long Range Single Motor", displayName: "Polestar 2 Long Range Single Motor", usableBatteryKWh: 82, wltpRangeKm: 650, peakDCChargingKW: 205),
        VehicleProfileTemplate(id: "polestar_2_standard_range_single_motor_my26", brand: "Polestar", modelName: "2 Standard Range Single Motor", displayName: "Polestar 2 Standard Range Single Motor", usableBatteryKWh: 67, wltpRangeKm: 554, peakDCChargingKW: 180),
        VehicleProfileTemplate(id: "polestar_3_long_range_dual_motor", brand: "Polestar", modelName: "3 Long Range Dual Motor", displayName: "Polestar 3 Long Range Dual Motor", usableBatteryKWh: 107, wltpRangeKm: 631, peakDCChargingKW: 250),
        VehicleProfileTemplate(id: "polestar_3_long_range_performance", brand: "Polestar", modelName: "3 Long Range Performance", displayName: "Polestar 3 Long Range Performance", usableBatteryKWh: 107, wltpRangeKm: 567, peakDCChargingKW: 250),
        VehicleProfileTemplate(id: "polestar_4_long_range_dual_motor", brand: "Polestar", modelName: "4 Long Range Dual Motor", displayName: "Polestar 4 Long Range Dual Motor", usableBatteryKWh: 94, wltpRangeKm: 590, peakDCChargingKW: 200),
        VehicleProfileTemplate(id: "polestar_4_long_range_single_motor", brand: "Polestar", modelName: "4 Long Range Single Motor", displayName: "Polestar 4 Long Range Single Motor", usableBatteryKWh: 94, wltpRangeKm: 620, peakDCChargingKW: 200),
        VehicleProfileTemplate(id: "porsche_macan_4", brand: "Porsche", modelName: "Macan 4 Electric", displayName: "Porsche Macan 4 Electric", usableBatteryKWh: 95, wltpRangeKm: 613, peakDCChargingKW: 270),
        VehicleProfileTemplate(id: "porsche_macan_e", brand: "Porsche", modelName: "Macan Electric", displayName: "Porsche Macan Electric", usableBatteryKWh: 95, wltpRangeKm: 640, peakDCChargingKW: 270),
        VehicleProfileTemplate(id: "porsche_taycan", brand: "Porsche", modelName: "Taycan", displayName: "Porsche Taycan", usableBatteryKWh: 82.3, wltpRangeKm: 500, peakDCChargingKW: 270),
        VehicleProfileTemplate(id: "porsche_taycan_4s", brand: "Porsche", modelName: "Taycan 4S", displayName: "Porsche Taycan 4S", usableBatteryKWh: 97, wltpRangeKm: 630, peakDCChargingKW: 320),
        VehicleProfileTemplate(id: "renault_4_52", brand: "Renault", modelName: "4 E-Tech 52 kWh", displayName: "Renault 4 E-Tech 52 kWh", usableBatteryKWh: 52, wltpRangeKm: 400, peakDCChargingKW: 100),
        VehicleProfileTemplate(id: "renault_5_40", brand: "Renault", modelName: "5 E-Tech 40 kWh", displayName: "Renault 5 E-Tech 40 kWh", usableBatteryKWh: 40, wltpRangeKm: 300, peakDCChargingKW: 80),
        VehicleProfileTemplate(id: "renault_5_52", brand: "Renault", modelName: "5 E-Tech 52 kWh", displayName: "Renault 5 E-Tech 52 kWh", usableBatteryKWh: 52, wltpRangeKm: 410, peakDCChargingKW: 100),
        VehicleProfileTemplate(id: "renault_megane_60", brand: "Renault", modelName: "Megane E-Tech 60 kWh", displayName: "Renault Megane E-Tech 60 kWh", usableBatteryKWh: 60, wltpRangeKm: 470, peakDCChargingKW: 130),
        VehicleProfileTemplate(id: "renault_scenic_60", brand: "Renault", modelName: "Scenic E-Tech 60 kWh", displayName: "Renault Scenic E-Tech 60 kWh", usableBatteryKWh: 60, wltpRangeKm: 430, peakDCChargingKW: 130),
        VehicleProfileTemplate(id: "renault_scenic_87", brand: "Renault", modelName: "Scenic E-Tech 87 kWh", displayName: "Renault Scenic E-Tech 87 kWh", usableBatteryKWh: 87, wltpRangeKm: 625, peakDCChargingKW: 150),
        VehicleProfileTemplate(id: "rivian_r1s_dual_large_gen2", brand: "Rivian", modelName: "R1S Dual Large", displayName: "Rivian R1S Dual Large", usableBatteryKWh: 108.5, wltpRangeKm: 529, peakDCChargingKW: 220),
        VehicleProfileTemplate(id: "rivian_r1s_dual_max_gen2", brand: "Rivian", modelName: "R1S Dual Max", displayName: "Rivian R1S Dual Max", usableBatteryKWh: 140, wltpRangeKm: 660, peakDCChargingKW: 220),
        VehicleProfileTemplate(id: "rivian_r1s_dual_standard_gen2", brand: "Rivian", modelName: "R1S Dual Standard", displayName: "Rivian R1S Dual Standard", usableBatteryKWh: 92.5, wltpRangeKm: 435, peakDCChargingKW: 200),
        VehicleProfileTemplate(id: "rivian_r1t_dual_large_gen2", brand: "Rivian", modelName: "R1T Dual Large", displayName: "Rivian R1T Dual Large", usableBatteryKWh: 108.5, wltpRangeKm: 566, peakDCChargingKW: 220),
        VehicleProfileTemplate(id: "rivian_r1t_dual_max_gen2", brand: "Rivian", modelName: "R1T Dual Max", displayName: "Rivian R1T Dual Max", usableBatteryKWh: 140, wltpRangeKm: 676, peakDCChargingKW: 220),
        VehicleProfileTemplate(id: "rivian_r1t_dual_standard_gen2", brand: "Rivian", modelName: "R1T Dual Standard", displayName: "Rivian R1T Dual Standard", usableBatteryKWh: 92.5, wltpRangeKm: 435, peakDCChargingKW: 200),
        VehicleProfileTemplate(id: "skoda_elroq_50", brand: "Skoda", modelName: "Elroq 50", displayName: "Skoda Elroq 50", usableBatteryKWh: 52, wltpRangeKm: 375, peakDCChargingKW: 145),
        VehicleProfileTemplate(id: "skoda_elroq_60", brand: "Skoda", modelName: "Elroq 60", displayName: "Skoda Elroq 60", usableBatteryKWh: 59, wltpRangeKm: 400, peakDCChargingKW: 105),
        VehicleProfileTemplate(id: "skoda_elroq_85", brand: "Skoda", modelName: "Elroq 85", displayName: "Skoda Elroq 85", usableBatteryKWh: 77, wltpRangeKm: 560, peakDCChargingKW: 175),
        VehicleProfileTemplate(id: "skoda_enyaq_60", brand: "Skoda", modelName: "Enyaq 60", displayName: "Skoda Enyaq 60", usableBatteryKWh: 59, wltpRangeKm: 430, peakDCChargingKW: 165),
        VehicleProfileTemplate(id: "skoda_enyaq_85", brand: "Skoda", modelName: "Enyaq 85", displayName: "Skoda Enyaq 85", usableBatteryKWh: 77, wltpRangeKm: 565, peakDCChargingKW: 135),
        VehicleProfileTemplate(id: "skoda_enyaq_85x", brand: "Skoda", modelName: "Enyaq 85x", displayName: "Skoda Enyaq 85x", usableBatteryKWh: 77, wltpRangeKm: 540, peakDCChargingKW: 175),
        VehicleProfileTemplate(id: "skoda_enyaq_rs", brand: "Skoda", modelName: "Enyaq RS", displayName: "Skoda Enyaq RS", usableBatteryKWh: 77, wltpRangeKm: 540, peakDCChargingKW: 175),
        VehicleProfileTemplate(id: "volkswagen_id3_pro", brand: "Volkswagen", modelName: "ID.3 Pro", displayName: "Volkswagen ID.3 Pro", usableBatteryKWh: 59, wltpRangeKm: 434, peakDCChargingKW: 165),
        VehicleProfileTemplate(id: "volkswagen_id3_pro_s", brand: "Volkswagen", modelName: "ID.3 Pro S", displayName: "Volkswagen ID.3 Pro S", usableBatteryKWh: 77, wltpRangeKm: 559, peakDCChargingKW: 175),
        VehicleProfileTemplate(id: "volkswagen_id3_pure", brand: "Volkswagen", modelName: "ID.3 Pure", displayName: "Volkswagen ID.3 Pure", usableBatteryKWh: 52, wltpRangeKm: 388, peakDCChargingKW: 145),
        VehicleProfileTemplate(id: "volkswagen_id4_pro", brand: "Volkswagen", modelName: "ID.4 Pro", displayName: "Volkswagen ID.4 Pro", usableBatteryKWh: 77, wltpRangeKm: 550, peakDCChargingKW: 175),
        VehicleProfileTemplate(id: "volkswagen_id5_pro", brand: "Volkswagen", modelName: "ID.5 Pro", displayName: "Volkswagen ID.5 Pro", usableBatteryKWh: 77, wltpRangeKm: 556, peakDCChargingKW: 175),
        VehicleProfileTemplate(id: "volkswagen_id7_pro", brand: "Volkswagen", modelName: "ID.7 Pro", displayName: "Volkswagen ID.7 Pro", usableBatteryKWh: 77, wltpRangeKm: 621, peakDCChargingKW: 175),
        VehicleProfileTemplate(id: "volkswagen_id7_pro_s", brand: "Volkswagen", modelName: "ID.7 Pro S", displayName: "Volkswagen ID.7 Pro S", usableBatteryKWh: 86, wltpRangeKm: 700, peakDCChargingKW: 200),
        VehicleProfileTemplate(id: "volkswagen_id_buzz_77", brand: "Volkswagen", modelName: "ID. Buzz 77 kWh", displayName: "Volkswagen ID. Buzz 77 kWh", usableBatteryKWh: 77, wltpRangeKm: 424, peakDCChargingKW: 170),
        VehicleProfileTemplate(id: "volkswagen_id_buzz_86_lwb", brand: "Volkswagen", modelName: "ID. Buzz 86 kWh LWB", displayName: "Volkswagen ID. Buzz 86 kWh LWB", usableBatteryKWh: 86, wltpRangeKm: 487, peakDCChargingKW: 200),
        VehicleProfileTemplate(id: "volvo_ec40_single_motor_er", brand: "Volvo", modelName: "EC40 Single Motor Extended Range", displayName: "Volvo EC40 Single Motor Extended Range", usableBatteryKWh: 79, wltpRangeKm: 583, peakDCChargingKW: 200),
        VehicleProfileTemplate(id: "volvo_ex30_single_motor", brand: "Volvo", modelName: "EX30 Single Motor", displayName: "Volvo EX30 Single Motor", usableBatteryKWh: 49, wltpRangeKm: 344, peakDCChargingKW: 134),
        VehicleProfileTemplate(id: "volvo_ex30_sm", brand: "Volvo", modelName: "EX30 Single Motor", displayName: "Volvo EX30 Single Motor", usableBatteryKWh: 49, wltpRangeKm: 344, peakDCChargingKW: 134),
        VehicleProfileTemplate(id: "volvo_ex30_single_motor_er", brand: "Volvo", modelName: "EX30 Single Motor Extended Range", displayName: "Volvo EX30 Single Motor Extended Range", usableBatteryKWh: 64, wltpRangeKm: 476, peakDCChargingKW: 153),
        VehicleProfileTemplate(id: "volvo_ex30_twin", brand: "Volvo", modelName: "EX30 Twin Motor", displayName: "Volvo EX30 Twin Motor Performance", usableBatteryKWh: 64, wltpRangeKm: 450, peakDCChargingKW: 153),
        VehicleProfileTemplate(id: "volvo_ex30_twin_motor_performance", brand: "Volvo", modelName: "EX30 Twin Motor Performance", displayName: "Volvo EX30 Twin Motor Performance", usableBatteryKWh: 64, wltpRangeKm: 450, peakDCChargingKW: 153),
        VehicleProfileTemplate(id: "volvo_ex40_sm", brand: "Volvo", modelName: "EX40 Single Motor", displayName: "Volvo EX40 Single Motor", usableBatteryKWh: 79, wltpRangeKm: 575, peakDCChargingKW: 205),
        VehicleProfileTemplate(id: "volvo_ex40_single_motor_er", brand: "Volvo", modelName: "EX40 Single Motor Extended Range", displayName: "Volvo EX40 Single Motor Extended Range", usableBatteryKWh: 79, wltpRangeKm: 576, peakDCChargingKW: 200),
        VehicleProfileTemplate(id: "volvo_ex40_twin_motor", brand: "Volvo", modelName: "EX40 Twin Motor", displayName: "Volvo EX40 Twin Motor", usableBatteryKWh: 79, wltpRangeKm: 537, peakDCChargingKW: 200),
        VehicleProfileTemplate(id: "volvo_ex90", brand: "Volvo", modelName: "EX90", displayName: "Volvo EX90", usableBatteryKWh: 107, wltpRangeKm: 600, peakDCChargingKW: 250),
        VehicleProfileTemplate(id: "volvo_ex90_twin_motor", brand: "Volvo", modelName: "EX90 Twin Motor", displayName: "Volvo EX90 Twin Motor", usableBatteryKWh: 107, wltpRangeKm: 614, peakDCChargingKW: 250),
        VehicleProfileTemplate(id: "tesla_model3_rwd", brand: "Tesla", modelName: "Model 3 RWD", displayName: "Tesla Model 3 RWD", usableBatteryKWh: 60.0, wltpRangeKm: 513, peakDCChargingKW: 170),
        VehicleProfileTemplate(id: "tesla_model3_lr_awd", brand: "Tesla", modelName: "Model 3 Long Range AWD", displayName: "Tesla Model 3 Long Range AWD", usableBatteryKWh: 79.0, wltpRangeKm: 629, peakDCChargingKW: 250),
        VehicleProfileTemplate(id: "tesla_modely_rwd", brand: "Tesla", modelName: "Model Y RWD", displayName: "Tesla Model Y RWD", usableBatteryKWh: 60.0, wltpRangeKm: 500, peakDCChargingKW: 170),
        VehicleProfileTemplate(id: "tesla_modely_lr_awd", brand: "Tesla", modelName: "Model Y Long Range AWD", displayName: "Tesla Model Y Long Range AWD", usableBatteryKWh: 79.0, wltpRangeKm: 622, peakDCChargingKW: 250),
        VehicleProfileTemplate(id: "byd_atto3", brand: "BYD", modelName: "Atto 3", displayName: "BYD Atto 3", usableBatteryKWh: 60.5, wltpRangeKm: 420, peakDCChargingKW: 88),
        VehicleProfileTemplate(id: "byd_seal", brand: "BYD", modelName: "Seal", displayName: "BYD Seal", usableBatteryKWh: 82.5, wltpRangeKm: 570, peakDCChargingKW: 150),
        VehicleProfileTemplate(id: "mg4_standard_range", brand: "MG", modelName: "MG4 Standard Range", displayName: "MG4 Standard Range", usableBatteryKWh: 49.0, wltpRangeKm: 350, peakDCChargingKW: 117),
        VehicleProfileTemplate(id: "mg4_long_range", brand: "MG", modelName: "MG4 Long Range", displayName: "MG4 Long Range", usableBatteryKWh: 64.0, wltpRangeKm: 520, peakDCChargingKW: 140)
    ]

    static let brands: [String] = templates.reduce(into: []) { brands, template in
        guard brands.contains(template.brand) == false else {
            return
        }

        brands.append(template.brand)
    }

    static func templates(forBrand brand: String) -> [VehicleProfileTemplate] {
        templates.filter { $0.brand == brand }
    }

    static func template(id: String) -> VehicleProfileTemplate? {
        templates.first { $0.id == id }
    }
}
